name: assignment4

on:
  workflow_dispatch:  # Triggered manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on a fresh Ubuntu environment

    steps:
      - name: Checkout repository  # Step 1: Checkout the code from your repository
        uses: actions/checkout@v2  # This allows GitHub Actions to access your repository

      - name: Set up Docker  # Step 2: Install Docker
        uses: docker/setup-buildx-action@v2  # Action to set up Docker for the job

      - name: Install Docker Compose  # Step 3: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose  # Make docker-compose executable

      - name: Build Docker images  # Step 4: Build Docker images for the stocks and capital-gains services
        id: build_images
        run: |
          start_time=$(date -Iminutes)  # Capture the start time
          echo "Start time: $start_time" > log.txt
          echo "Yossi Peleg" >> log.txt  # You can change this if needed


          # Build images using docker-compose
          set +e
          docker-compose -f docker-compose.yml build 
          build_status=$?
          if [ $build_status -eq 0 ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
          fi

          docker image ls  # To list the images built
      
      - name: Docker-Conpose up
        run: |
          # Using detached mode:
          docker-compose -f docker-compose.yml up -d
          docker ps #For verification
          containers_status=$?
          set -e
          if [ $containers_status -eq 0 ]; then
            echo "Containers up and running" >> log.txt
          else
            echo "Containers failed to run" >> log.txt
          fi

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt

