name: assignment4

on:
  workflow_dispatch:  # Triggered manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on a fresh Ubuntu environment

    steps:
      - name: Checkout repository  # Step 1: Checkout the code from your repository
        uses: actions/checkout@v2  # This allows GitHub Actions to access your repository

      - name: Set up Docker  # Step 2: Install Docker
        uses: docker/setup-buildx-action@v2  # Action to set up Docker for the job

      - name: Install Docker Compose  # Step 3: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose  # Make docker-compose executable

      - name: Build Docker images  # Step 4: Build Docker images for the services
        id: build_images
        run: |
          start_time=$(date -Iminutes)  # Capture the start time
          echo "Start time: $start_time" > $GITHUB_WORKSPACE/log.txt  # Save log.txt to the workspace
          echo "Yossi Peleg" >> $GITHUB_WORKSPACE/log.txt  # Add your name

          set +e
          docker-compose -f docker-compose.yml build  # Build images
          build_status=$?
          set -e

          if [ $build_status -eq 0 ]; then
            echo "image successfully built" >> $GITHUB_WORKSPACE/log.txt
          else
            echo "image not able to be built" >> $GITHUB_WORKSPACE/log.txt
          fi

      - name: Docker Compose up  # Step 5: Start the application
        if: success()
        run: |
          set +e
          docker-compose -f docker-compose.yml up -d
          up_status=$?
          set -e

          if [ $up_status -eq 0 ]; then
            echo "Containers up and running" >> $GITHUB_WORKSPACE/log.txt  # Save to workspace log.txt
          else
            echo "Containers failed to run" >> $GITHUB_WORKSPACE/log.txt
          fi

      - name: Upload log.txt artifact  # Step 6: Upload the log.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: ignore
          path: log.txt  # Upload log.txt to share with the next job

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job to complete

    steps:
      - name: Checkout repository  # Step 1: Checkout the code from your repository
        uses: actions/checkout@v2  # This allows GitHub Actions to access your repository

      - name: Set up Python environment  # Step 2: Install Python and pytest
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install pytest

      - name: Download log.txt artifact  # Step 3: Download the log.txt artifact from the build job
        uses: actions/download-artifact@v4
        with:
          name: ignore  # This should match the artifact name used in the build job
          path: log.txt  # Save it in the workspace directory

      - name: Run and log pytest results  # Step 5: Run pytest and append results to log.txt
        run: |
          pytest tests/assn4_tests.py > assn4_test_results.txt || true
          cat assn4_test_results.txt
          if grep -q "FAILURES" assn4_test_results.txt; then
            echo "tests failed" >> $GITHUB_WORKSPACE/log.txt  # Append to log.txt in workspace
          else
            echo "tests succeeded" >> $GITHUB_WORKSPACE/log.txt
          fi

      - name: Upload updated log.txt  # Step 6: Upload the updated log.txt as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt  # Upload updated log.txt after modification

      - name: Upload test results  # Step 7: Upload test results as a separate artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: assn4_test_results.txt
