name: assignment4

on:
  workflow_dispatch:  # Triggered manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on a fresh Ubuntu environment

    steps:
      - name: Checkout repository  # Step 1: Checkout the code from your repository
        uses: actions/checkout@v2  # This allows GitHub Actions to access your repository

      - name: Set up Docker  # Step 2: Install Docker
        uses: docker/setup-buildx-action@v2  # Action to set up Docker for the job

      - name: Install Docker Compose  # Step 3: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose  # Make docker-compose executable

      - name: Build Docker images  # Step 4: Build Docker images for the services
        id: build_images
        run: |
          start_time=$(date -Iminutes)  # Capture the start time
          echo "Start time: $start_time" > log.txt  # Overwrite log.txt initially to set start time
          echo "Yossi Peleg" >> log.txt  # Add your name

          set +e
          docker-compose -f docker-compose.yml build  # Build images
          build_status=$?
          set -e

          if [ $build_status -eq 0 ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
          fi

      - name: Upload log.txt as artifact  # Upload the log.txt file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ignore  # The artifact's name
          path: log.txt  # The file to upload

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job to complete

    steps:
      - name: Checkout repository  # Step 1: Checkout the code from your repository
        uses: actions/checkout@v2  # This allows GitHub Actions to access your repository


      - name: Install Docker Compose  # Step 3: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose  # Make docker-compose executable

      - name: Set up Python environment  # Step 2: Install Python and pytest
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install pytest

      - name: Download log artifact  # Step 3: Download the log.txt file from the build job
        uses: actions/download-artifact@v4
        with:
          name: ignore  # The artifact's name
          path: ./  # Download it to the current directory

      - name: Docker Compose up  # Step 5: Start the application
        run: |
          set +e
          docker-compose -f docker-compose.yml up -d
          up_status=$?
          set -e
  
          if [ $up_status -eq 0 ]; then
            echo "Containers up and running" >> log.txt  # Append status
          else
            echo "Containers failed to run" >> log.txt  # Append failure status
          fi

      - name: Wait for stocks service to be ready  # Step 6: Wait until the service is ready
        run: |
           for i in {1..30}; do  # Retry 30 times
              if curl --silent --fail http://localhost:5001/stocks; then
                echo "All services are up!"
                break
              else
                echo "Waiting for services to be available..."
                sleep 5
              fi
            done

      - name: Check running containers with docker ps  # Step 4: Verify containers are running
        run: |
          echo "Listing all running containers:"
          docker ps  # List all running containers
  

      - name: Run tests  # Step 4: Run pytest
        run: |
          pytest tests/assn4_tests.py > assn4_test_results.txt || true
          cat assn4_test_results.txt

      - name: Log test results status  # Update log.txt with test results
        run: |
          if grep -q "FAILURES" assn4_test_results.txt; then
            echo "tests failed" >> log.txt  # Append "tests failed"
          else
            echo "tests succeeded" >> log.txt  # Append "tests succeeded"
          fi

      
      - name: Upload test results  # Upload the pytest results file
        uses: actions/upload-artifact@v4
        with:
          name: test-results  # Artifact name for test results
          path: assn4_test_results.txt

      - name: Upload log file  # Upload the log file
        uses: actions/upload-artifact@v4
        with:
          name: log  # Artifact name for the log file
          path: log.txt
  query:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose  # Ensure Docker Compose is installed again
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose  # Make docker-compose executable

    - name: Start services with Docker Compose  # Deploy the services again
      run: |
        docker-compose -f docker-compose.yml up --build -d  # Start services in detached mode

    - name: Wait for stocks service to be ready  # Step 6: Wait until the service is ready
      run: |
           for i in {1..30}; do  # Retry 30 times
              if curl --silent --fail http://localhost:5001/stocks; then
                echo "All services are up!"
                break
              else
                echo "Waiting for services to be available..."
                sleep 5
              fi
            done

    - name: Check running containers with docker ps  # Step 4: Verify containers are running
      run: |
          echo "Listing all running containers:"
          docker ps  # List all running containers
    

    - name: Get stocks before POST requests
      run: |
        echo "Getting stock list before POST requests"
        curl -X GET http://localhost:5001/stocks

    - name: Execute 6 POST requests to add stocks
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"name": "NVIDIA Corporation", "symbol": "NVDA", "purchase price": 134.66, "purchase date": "18-06-2024", "shares": 7}' http://localhost:5001/stocks
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Apple Inc.", "symbol": "AAPL", "purchase price": 183.63, "purchase date": "22-02-2024", "shares": 19}' http://localhost:5001/stocks
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Alphabet Inc.", "symbol": "GOOG", "purchase price": 140.12, "purchase date": "24-10-2024", "shares": 14}' http://localhost:5001/stocks
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Tesla, Inc.", "symbol": "TSLA", "purchase price": 194.58, "purchase date": "28-11-2022", "shares": 32}' http://localhost:5001/stocks
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Microsoft Corporation", "symbol": "MSFT", "purchase price": 420.55, "purchase date": "09-02-2024", "shares": 35}' http://localhost:5001/stocks
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Intel Corporation", "symbol": "INTC", "purchase price": 19.15, "purchase date": "13-01-2025", "shares": 10}' http://localhost:5001/stocks

    - name: Get stocks after POST requests
      run: |
        echo "Getting stock list after POST requests"
        curl -X GET http://localhost:5001/stocks


    - name: Read query.txt and process each query
      id: query-processing
      run: |
          while IFS= read -r line; do
            # Extract the service and query string from the line
            service=$(echo $line | cut -d':' -f1)
            query_string=$(echo $line | cut -d':' -f2)
  
            # Check if the service is "stocks" or "capital-gains"
            if [ "$service" == "stocks" ]; then
              echo "curl -X GET http://localhost:5001/stocks?$query_string"
            elif [ "$service" == "capital-gains" ]; then
              echo "curl -X GET http://localhost:5003/capital-gains?$query_string"
            else
              echo "Invalid service: $service"
            fi
          done < query.txt